/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sandbox

import io.kotest.matchers.shouldBe
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = App()

        classUnderTest.greeting shouldBe "Hello World!"
    }
}
